version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: oasis_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: 'false'
    container_name: oasis_app_proxy_1

  server:
    image: machengim/oasis:latest
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/opt/oasis/data
      - ${UMBREL_ROOT}/data/storage:/home/storage
      - ${UMBREL_ROOT}:/umbrel_root:rw
    environment:
      - OASIS_PORT=8000
      - OASIS_DATABASE=/opt/oasis/data/oasis.db
      - OASIS_ROOT=/home/storage
      - TZ=Europe/Berlin
    container_name: oasis_server_1